style: gitlab
template: CHANGELOG.tpl.md
info:
  title: "@my-scope/usage"
  repository_url: https://github.com/rizalibnu/lerna-conventional-commits-example
options:
  issues:
    prefix:
      - #
  commits:
    filters:
      Type:
        - feature
        - feat
        - fix
        - hotfix
        - perf
        - performance
        - refactor
  commit_groups:
    title_maps:
      feature: Features
      feat: Features
      fix: Bug Fixes
      hotfix: Bug Fixes
      perf: Performance Improvements
      performance: Performance Improvements
      refactor: Code Refactoring
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE